In [1]:
import torch

In [ ]:
torch.__version__

'2.1.0+cu118'

In [ ]:
import torch

#Scalar, Vector, Matrix, Tensor

In [ ]:
scalar = torch.tensor(7)
print(scalar.ndim, "\n" ,scalar.shape, "\n", scalar.item())

0 
 torch.Size([]) 
 7


In [ ]:
vector = torch.tensor([1,2,3])
print(vector.ndim, "\n", vector.shape)

1 
 torch.Size([3])


In [ ]:
matrix = torch.tensor([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(matrix.ndim, matrix.shape)

2 torch.Size([3, 5])


In [ ]:
tensor = torch.tensor([[[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]]])

print(tensor.ndim, "\n", tensor.shape)

3 
 torch.Size([4, 3, 6])


#Random Tensors

In [ ]:
ranTensor = torch.rand(3,5)
ranTensor

tensor([[0.1331, 0.9179, 0.6484, 0.9359, 0.7713],
        [0.8510, 0.3971, 0.2049, 0.8235, 0.4495],
        [0.0118, 0.0437, 0.3168, 0.9566, 0.9599]])

In [ ]:
onesTen = torch.ones(3,4)
onesTen

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zerTen = torch.zeros(3,4)
zerTen

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Range Tensors

In [ ]:
rangeTensor = torch.arange(0, 23, 2)
rangeTensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
zerosRangeTen = torch.zeros_like(rangeTensor)
zerosRangeTen

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensors Parameters

In [ ]:
tempTensor = torch.rand(3,4, dtype=torch.float64,
                    device='cpu',
                    requires_grad=False)
print(tempTensor)

print('\n')
tempTensor = tempTensor.type(torch.float16)
print(tempTensor)

tensor([[0.8469, 0.5901, 0.4149, 0.6793],
        [0.4764, 0.9268, 0.7465, 0.0875],
        [0.0773, 0.8230, 0.5801, 0.4959]], dtype=torch.float64)


tensor([[0.8467, 0.5898, 0.4148, 0.6792],
        [0.4763, 0.9268, 0.7466, 0.0875],
        [0.0773, 0.8232, 0.5801, 0.4958]], dtype=torch.float16)


# Operations On Tensors

In [ ]:
tensorForOper = torch.tensor([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
tensorForOper

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
tensorForOper + 10 #tensorForOper.add(10)

tensor([[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]])

In [ ]:
tensorForOper - 10

tensor([[-9, -8, -7],
        [-9, -8, -7],
        [-9, -8, -7],
        [-9, -8, -7]])

In [ ]:
tensorForOper/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000]])

In [ ]:
tensorForOper * 10 #tensorForOper.mul(10)

tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])

# Matrix multiplication

1 Tensors Innder Dimensions Must Match                                          
2 Tensor will have dimension of outer dimensions: tensor2 number of elements, tensor1 number of lists

In [6]:
mulTen = torch.rand(3,2)
mulTen2 = torch.rand(2,5)
torch.matmul(mulTen, mulTen2)

tensor([[0.4486, 0.5130, 0.3483, 0.4494, 0.2641],
        [0.7432, 0.5390, 0.5886, 0.8125, 0.5297],
        [0.5406, 0.6291, 0.4193, 0.5392, 0.3150]])

In [9]:
mulTenNext = torch.rand(2,3)
mulTenNext2 = torch.rand(2,3)
try:
  torch.matmul(mulTenNext, mulTenNext2)
except:
  multiptication = torch.matmul(mulTenNext, mulTenNext2.reshape(3,2))
multiptication

tensor([[0.6701, 0.1410],
        [1.0425, 0.1722]])