<a href="https://colab.research.google.com/github/Sprt6I/pytorch-Tutorial/blob/main/NEXT_MyExercises_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [4]:
x = torch.rand(3,3,2)

In [6]:
x.reshape(1, 18).squeeze()

tensor([0.9997, 0.5868, 0.3895, 0.0641, 0.0286, 0.7317, 0.3467, 0.0858, 0.1982,
        0.2508, 0.1735, 0.9187, 0.2680, 0.9264, 0.1001, 0.3997, 0.2803, 0.2919])

In [7]:
x = torch.stack([x,x,x,x], dim = 0)

In [10]:
x.shape

torch.Size([4, 3, 3, 2])

In [11]:
y = x.permute(3,1,2,0)
y.shape

torch.Size([2, 3, 3, 4])

In [13]:
x = x.reshape(2,9,4)

In [14]:
x[:, 0]

tensor([[0.9997, 0.5868, 0.3895, 0.0641],
        [0.9997, 0.5868, 0.3895, 0.0641]])

In [15]:
x.max(), x.min()

(tensor(0.9997), tensor(0.0286))

In [16]:
x.argmax(), x.argmin()

(tensor(0), tensor(4))

In [17]:
x.mean(), x.median()

(tensor(0.3911), tensor(0.2803))

In [19]:
torch.zeros_like(x), torch.ones_like(x)

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [

In [20]:
x+1

tensor([[[1.9997, 1.5868, 1.3895, 1.0641],
         [1.0286, 1.7317, 1.3467, 1.0858],
         [1.1982, 1.2508, 1.1735, 1.9187],
         [1.2680, 1.9264, 1.1001, 1.3997],
         [1.2803, 1.2919, 1.9997, 1.5868],
         [1.3895, 1.0641, 1.0286, 1.7317],
         [1.3467, 1.0858, 1.1982, 1.2508],
         [1.1735, 1.9187, 1.2680, 1.9264],
         [1.1001, 1.3997, 1.2803, 1.2919]],

        [[1.9997, 1.5868, 1.3895, 1.0641],
         [1.0286, 1.7317, 1.3467, 1.0858],
         [1.1982, 1.2508, 1.1735, 1.9187],
         [1.2680, 1.9264, 1.1001, 1.3997],
         [1.2803, 1.2919, 1.9997, 1.5868],
         [1.3895, 1.0641, 1.0286, 1.7317],
         [1.3467, 1.0858, 1.1982, 1.2508],
         [1.1735, 1.9187, 1.2680, 1.9264],
         [1.1001, 1.3997, 1.2803, 1.2919]]])

In [21]:
x+1, x-1, x*2, x/2

(tensor([[[1.9997, 1.5868, 1.3895, 1.0641],
          [1.0286, 1.7317, 1.3467, 1.0858],
          [1.1982, 1.2508, 1.1735, 1.9187],
          [1.2680, 1.9264, 1.1001, 1.3997],
          [1.2803, 1.2919, 1.9997, 1.5868],
          [1.3895, 1.0641, 1.0286, 1.7317],
          [1.3467, 1.0858, 1.1982, 1.2508],
          [1.1735, 1.9187, 1.2680, 1.9264],
          [1.1001, 1.3997, 1.2803, 1.2919]],
 
         [[1.9997, 1.5868, 1.3895, 1.0641],
          [1.0286, 1.7317, 1.3467, 1.0858],
          [1.1982, 1.2508, 1.1735, 1.9187],
          [1.2680, 1.9264, 1.1001, 1.3997],
          [1.2803, 1.2919, 1.9997, 1.5868],
          [1.3895, 1.0641, 1.0286, 1.7317],
          [1.3467, 1.0858, 1.1982, 1.2508],
          [1.1735, 1.9187, 1.2680, 1.9264],
          [1.1001, 1.3997, 1.2803, 1.2919]]]),
 tensor([[[-3.3003e-04, -4.1316e-01, -6.1050e-01, -9.3588e-01],
          [-9.7136e-01, -2.6833e-01, -6.5327e-01, -9.1421e-01],
          [-8.0179e-01, -7.4918e-01, -8.2652e-01, -8.1342e-02],
          

In [22]:
new = torch.rand(2,3,4)
new1 = torch.rand(2,3,4)

In [23]:
new1 = new1.permute(2,0,1)
new1.shape

torch.Size([4, 2, 3])

In [27]:
new.shape, new1.shape

(torch.Size([2, 3, 4]), torch.Size([4, 2, 3]))

In [28]:
new2 = torch.matmul(new, new1.transpose(0,1))
new2.shape

torch.Size([2, 3, 3])