<a href="https://colab.research.google.com/github/Sprt6I/pytorch-Tutorial/blob/main/NEXT_00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import torch

In [36]:
torch.__version__

'2.1.0+cu118'

In [37]:
import torch

#Scalar, Vector, Matrix, Tensor

In [38]:
scalar = torch.tensor(7)
print(scalar.ndim, "\n" ,scalar.shape, "\n", scalar.item())

0 
 torch.Size([]) 
 7


In [39]:
vector = torch.tensor([1,2,3])
print(vector.ndim, "\n", vector.shape)

1 
 torch.Size([3])


In [40]:
matrix = torch.tensor([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(matrix.ndim, matrix.shape)

2 torch.Size([3, 5])


In [41]:
tensor = torch.tensor([[[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]],
                       [[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]]])

print(tensor.ndim, "\n", tensor.shape)

3 
 torch.Size([4, 3, 6])


#Random Tensors

In [42]:
ranTensor = torch.rand(3,5)
ranTensor

tensor([[0.5302, 0.6676, 0.6751, 0.1946, 0.9560],
        [0.4009, 0.7532, 0.1672, 0.8877, 0.5089],
        [0.5871, 0.6094, 0.7084, 0.9080, 0.9623]])

In [43]:
onesTen = torch.ones(3,4)
onesTen

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
zerTen = torch.zeros(3,4)
zerTen

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Range Tensors

In [45]:
rangeTensor = torch.arange(0, 23, 2)
rangeTensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [46]:
zerosRangeTen = torch.zeros_like(rangeTensor)
zerosRangeTen

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensors Parameters

In [47]:
tempTensor = torch.rand(3,4, dtype=torch.float64,
                    device='cpu',
                    requires_grad=False)
print(tempTensor)

print('\n')
tempTensor = tempTensor.type(torch.float16)
print(tempTensor)

tensor([[0.3971, 0.2462, 0.8237, 0.3299],
        [0.9044, 0.3613, 0.3703, 0.4991],
        [0.9551, 0.2219, 0.9824, 0.3770]], dtype=torch.float64)


tensor([[0.3972, 0.2462, 0.8237, 0.3298],
        [0.9043, 0.3613, 0.3704, 0.4990],
        [0.9551, 0.2219, 0.9824, 0.3770]], dtype=torch.float16)


# Operations On Tensors

In [48]:
tensorForOper = torch.tensor([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
tensorForOper

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [49]:
tensorForOper + 10 #tensorForOper.add(10)

tensor([[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]])

In [50]:
tensorForOper - 10

tensor([[-9, -8, -7],
        [-9, -8, -7],
        [-9, -8, -7],
        [-9, -8, -7]])

In [51]:
tensorForOper/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000]])

In [52]:
tensorForOper * 10 #tensorForOper.mul(10)

tensor([[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]])

# Matrix multiplication

1 Tensors Innder Dimensions Must Match                                          
2 Tensor will have dimension of outer dimensions: tensor2 number of elements, tensor1 number of lists

In [53]:
mulTen = torch.rand(3,2)
mulTen2 = torch.rand(2,5)
torch.matmul(mulTen, mulTen2)

tensor([[0.2852, 0.3571, 0.3097, 0.5869, 0.2213],
        [0.9201, 0.5756, 0.6634, 0.8736, 0.4183],
        [0.3796, 0.5321, 0.4453, 0.8817, 0.3237]])

In [54]:
mulTenNext = torch.rand(2,3)
mulTenNext2 = torch.rand(2,3)
try:
  torch.matmul(mulTenNext, mulTenNext2)
except:
  multiptication = torch.matmul(mulTenNext, mulTenNext2.reshape(3,2))
multiptication

tensor([[1.6050, 2.0181],
        [1.0359, 1.3552]])

# Tensors Aggregations

In [55]:
x = torch.rand(3,4)
x

tensor([[0.4497, 0.4748, 0.1238, 0.2725],
        [0.5201, 0.5179, 0.2549, 0.0673],
        [0.9419, 0.4294, 0.1944, 0.6842]])

In [56]:
x.min(), x.max()

(tensor(0.0673), tensor(0.9419))

In [57]:
x.mean(), x.median(), x.sum()

(tensor(0.4109), tensor(0.4294), tensor(4.9310))

In [58]:
x.argmin(), x.argmax()

(tensor(7), tensor(8))

# reshape, squeeze, unsqueeze, stack, view, permute Tensors

In [66]:
newTensor = torch.rand(4,3,2)

In [68]:
newTensor = newTensor.reshape(1,24)
newTensor.shape

torch.Size([1, 24])

In [71]:
newTensor = newTensor.squeeze(dim=0)
newTensor.shape

torch.Size([24])

In [72]:
newTensor = newTensor.unsqueeze(dim=0)
newTensor.shape

torch.Size([1, 24])

In [75]:
torch.stack([newTensor,newTensor,newTensor,newTensor])

tensor([[[0.6942, 0.6625, 0.3593, 0.7688, 0.4221, 0.8563, 0.4342, 0.0354,
          0.3532, 0.8426, 0.8060, 0.9441, 0.1262, 0.0149, 0.0405, 0.6452,
          0.6240, 0.3388, 0.4566, 0.6296, 0.4305, 0.2474, 0.5737, 0.5669]],

        [[0.6942, 0.6625, 0.3593, 0.7688, 0.4221, 0.8563, 0.4342, 0.0354,
          0.3532, 0.8426, 0.8060, 0.9441, 0.1262, 0.0149, 0.0405, 0.6452,
          0.6240, 0.3388, 0.4566, 0.6296, 0.4305, 0.2474, 0.5737, 0.5669]],

        [[0.6942, 0.6625, 0.3593, 0.7688, 0.4221, 0.8563, 0.4342, 0.0354,
          0.3532, 0.8426, 0.8060, 0.9441, 0.1262, 0.0149, 0.0405, 0.6452,
          0.6240, 0.3388, 0.4566, 0.6296, 0.4305, 0.2474, 0.5737, 0.5669]],

        [[0.6942, 0.6625, 0.3593, 0.7688, 0.4221, 0.8563, 0.4342, 0.0354,
          0.3532, 0.8426, 0.8060, 0.9441, 0.1262, 0.0149, 0.0405, 0.6452,
          0.6240, 0.3388, 0.4566, 0.6296, 0.4305, 0.2474, 0.5737, 0.5669]]])